/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signed in person, tenant memberships and staff roles
         * @description First sign in with a verified email activates pending invitations for that email.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Get tenant profile */
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile (only before verification is submitted) */
        patch: operations["updateTenant"];
        trace?: never;
    };
    "/tenants/{tenant_id}/departments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List departments */
        get: operations["listDepartments"];
        put?: never;
        /** Create department */
        post: operations["createDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/departments/{department_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                department_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename department */
        patch: operations["updateDepartment"];
        trace?: never;
    };
    "/tenants/{tenant_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List agents */
        get: operations["listAgents"];
        put?: never;
        /** Create agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                agent_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update or deactivate agent */
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/tenants/{tenant_id}/calling-numbers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List calling numbers */
        get: operations["listCallingNumbers"];
        put?: never;
        /** Add calling number for verification */
        post: operations["addCallingNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/calling-numbers/{number_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                number_id: components["parameters"]["NumberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop using a calling number */
        post: operations["revokeCallingNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Verification evidence and latest request */
        get: operations["getVerification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/verification/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload evidence (PDF, PNG or JPEG, at most 5 MB) */
        post: operations["uploadVerificationDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/verification/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove evidence (not while a request is under review) */
        delete: operations["deleteVerificationDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/verification/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit evidence for RingSays review */
        post: operations["submitVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List portal users */
        get: operations["listPortalUsers"];
        put?: never;
        /** Invite a person by email */
        post: operations["invitePortalUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change roles, agent link or status */
        patch: operations["updatePortalUser"];
        trace?: never;
    };
    "/tenants/{tenant_id}/purpose-codes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Purpose code catalogue with review state */
        get: operations["listTenantPurposeCodes"];
        put?: never;
        /** Propose a purpose code; enters RingSays review */
        post: operations["proposeTenantPurposeCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/purpose-codes/{code}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                code: components["parameters"]["Code"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire a purpose code; new intents can no longer use it */
        post: operations["retirePurposeCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/api-clients": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List API credentials (secrets never returned) */
        get: operations["listApiClients"];
        put?: never;
        /** Create API credentials; secret shown once */
        post: operations["createApiClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/api-clients/{client_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                client_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke API credentials (takes effect within 30 seconds) */
        post: operations["revokeApiClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/webhook-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List webhook endpoints */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /** Create webhook endpoint; signing secret shown once */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/webhook-endpoints/{endpoint_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                endpoint_id: components["parameters"]["EndpointId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop sending to an endpoint; queued deliveries are not sent */
        post: operations["disableWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/webhook-endpoints/{endpoint_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                endpoint_id: components["parameters"]["EndpointId"];
            };
            cookie?: never;
        };
        /** Delivery log, newest first */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/webhook-deliveries/{delivery_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                delivery_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a delivered or dead webhook again with the same event id */
        post: operations["replayWebhookDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/intents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Intents, newest first. AGENT role sees only intents it sent. */
        get: operations["monitorIntents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/intents/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Counts by status and channel since a time (default last 24 hours) */
        get: operations["monitorSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/intents/{intent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                intent_id: string;
            };
            cookie?: never;
        };
        /** Intent with status history, delivery attempts and webhooks */
        get: operations["monitorIntentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** List audit events, newest first */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/audit-events/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Recompute the tenant's audit hash chain */
        get: operations["verifyAuditChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/audit-events/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        /** Full audit log as CSV, oldest first, with hashes for independent verification */
        get: operations["exportAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backoffice/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All tenants in this region */
        get: operations["backofficeListTenants"];
        put?: never;
        /** Onboard an organisation and invite its first administrator (RS_ADMIN) */
        post: operations["backofficeCreateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backoffice/tenants/{tenant_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend; API access ends within 30 seconds (RS_ADMIN) */
        post: operations["backofficeSuspendTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backoffice/tenants/{tenant_id}/reinstate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lift a suspension (RS_ADMIN) */
        post: operations["backofficeReinstateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Items waiting for a RingSays decision, oldest first */
        get: operations["reviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/verifications/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        /** Tenant profile and evidence for a verification request */
        get: operations["reviewGetVerification"];
        put?: never;
        /** Approve (tenant becomes VERIFIED) or reject with reason */
        post: operations["reviewDecideVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** Download evidence file */
        get: operations["reviewDownloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/purpose-codes/{tenant_id}/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                code: components["parameters"]["Code"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a proposed purpose code */
        post: operations["reviewPurposeCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/calling-numbers/{number_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number_id: components["parameters"]["NumberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a calling number after checking operator registration */
        post: operations["reviewCallingNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TenantRole: "TENANT_ADMIN" | "INTEGRATION_ADMIN" | "SUPERVISOR" | "AGENT" | "COMPLIANCE";
        /** @enum {string} */
        StaffRole: "RS_REVIEWER" | "RS_ADMIN";
        /**
         * @description Derived from roles; the portal uses it to show or hide actions. The API enforces it.
         * @enum {string}
         */
        Permission: "org.read" | "org.manage" | "users.manage" | "catalogue.propose" | "integration.read" | "integration.manage" | "intents.read_all" | "intents.read_own" | "audit.read";
        /** @enum {string} */
        TenantStatus: "PENDING" | "VERIFIED" | "SUSPENDED";
        /** @enum {string} */
        Sector: "BANK" | "INSURANCE" | "FINANCE" | "GOVERNMENT";
        /** @enum {string} */
        Scope: "intents:write" | "intents:read" | "catalogue:read" | "catalogue:write";
        Reason: {
            reason: string;
        };
        Decision: {
            /** @enum {string} */
            decision: "APPROVE" | "REJECT";
            reason: string;
        };
        Me: {
            email: string;
            display_name?: string | null;
            memberships: {
                /** Format: uuid */
                tenant_id: string;
                legal_name: components["schemas"]["LocalisedText"];
                verification_status: components["schemas"]["TenantStatus"];
                roles: components["schemas"]["TenantRole"][];
                permissions: components["schemas"]["Permission"][];
                agent_id?: string | null;
            }[];
            staff_roles: components["schemas"]["StaffRole"][];
        };
        Tenant: {
            /** Format: uuid */
            tenant_id: string;
            legal_name: components["schemas"]["LocalisedText"];
            commercial_registration?: string | null;
            domain?: string | null;
            sector: components["schemas"]["Sector"];
            /** @enum {string} */
            residency_region: "KSA" | "IN" | "AE" | "EU";
            verification_status: components["schemas"]["TenantStatus"];
            suspended_reason?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        TenantUpdate: {
            legal_name?: components["schemas"]["LocalisedText"];
            commercial_registration?: string;
            domain?: string;
        };
        TenantCreate: {
            legal_name: components["schemas"]["LocalisedText"];
            sector: components["schemas"]["Sector"];
            domain?: string;
            /** Format: email */
            admin_email: string;
            admin_name?: string;
        };
        Department: {
            /** Format: uuid */
            department_id: string;
            name: components["schemas"]["LocalisedText"];
        };
        DepartmentInput: {
            name: components["schemas"]["LocalisedText"];
        };
        Agent: {
            agent_id: string;
            display_name: components["schemas"]["LocalisedText"];
            /** Format: uuid */
            department_id: string;
            /** @description Tenant internal reference; no personal phone stored. */
            employee_ref?: string | null;
            active: boolean;
        };
        AgentInput: {
            agent_id: string;
            display_name: components["schemas"]["LocalisedText"];
            /** Format: uuid */
            department_id: string;
            employee_ref?: string;
        };
        AgentUpdate: {
            display_name?: components["schemas"]["LocalisedText"];
            /** Format: uuid */
            department_id?: string;
            employee_ref?: string | null;
            active?: boolean;
        };
        CallingNumber: {
            /** Format: uuid */
            number_id: string;
            /** @description Business number with middle digits hidden, for example +9661•••••000. */
            phone_masked: string;
            /** Format: uuid */
            department_id?: string | null;
            /** @enum {string} */
            status: "PENDING_VERIFICATION" | "VERIFIED" | "REVOKED";
            /** @description Whether number is registered in operator caller name programme. */
            cst_entity_name_registered: boolean;
            review_reason?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CallingNumberInput: {
            phone: components["schemas"]["E164"];
            /** Format: uuid */
            department_id?: string;
            cst_entity_name_registered: boolean;
        };
        /** @enum {string} */
        DocumentKind: "COMMERCIAL_REGISTRATION" | "REGULATOR_LICENCE" | "AUTHORISATION_LETTER" | "DOMAIN_PROOF" | "OTHER";
        VerificationDocument: {
            /** Format: uuid */
            document_id: string;
            kind: components["schemas"]["DocumentKind"];
            reference?: string | null;
            file_name: string;
            /** @enum {string} */
            content_type: "application/pdf" | "image/png" | "image/jpeg";
            size_bytes: number;
            sha256: string;
            /** Format: date-time */
            uploaded_at: string;
        };
        VerificationRequest: {
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            status: "SUBMITTED" | "APPROVED" | "REJECTED";
            /** Format: date-time */
            submitted_at: string;
            /** Format: date-time */
            decided_at?: string | null;
            decision_reason?: string | null;
        };
        Verification: {
            tenant_status: components["schemas"]["TenantStatus"];
            documents: components["schemas"]["VerificationDocument"][];
            required_kinds: components["schemas"]["DocumentKind"][];
            latest_request: components["schemas"]["VerificationRequest"] | null;
        };
        VerificationReview: {
            request: components["schemas"]["VerificationRequest"];
            tenant: components["schemas"]["Tenant"];
            documents: components["schemas"]["VerificationDocument"][];
        };
        PortalUser: {
            /** Format: uuid */
            user_id: string;
            email: string;
            display_name?: string | null;
            roles: components["schemas"]["TenantRole"][];
            agent_id?: string | null;
            /** @enum {string} */
            status: "INVITED" | "ACTIVE" | "DISABLED";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_sign_in_at?: string | null;
        };
        PortalUserInvite: {
            /** Format: email */
            email: string;
            display_name?: string;
            roles: components["schemas"]["TenantRole"][];
            /** @description Required when roles include AGENT. */
            agent_id?: string;
        };
        PortalUserUpdate: {
            roles?: components["schemas"]["TenantRole"][];
            agent_id?: string | null;
            /** @enum {string} */
            status?: "ACTIVE" | "DISABLED";
        };
        AdminPurposeCode: components["schemas"]["PurposeCode"] & {
            /** Format: date-time */
            proposed_at?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            review_reason?: string | null;
        };
        ApiClient: {
            client_id: string;
            label: string;
            scopes: components["schemas"]["Scope"][];
            active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        /** @enum {string} */
        WebhookEventType: "intent.delivered" | "intent.accepted" | "intent.rescheduled" | "intent.scheduled" | "intent.declined" | "intent.expired" | "intent.cancelled" | "outcome.recorded";
        WebhookEndpoint: {
            /** Format: uuid */
            endpoint_id: string;
            url: string;
            events: components["schemas"]["WebhookEventType"][];
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        WebhookDeliveryStatus: "PENDING" | "SENDING" | "DELIVERED" | "DEAD";
        WebhookDelivery: {
            delivery_id: number;
            /** Format: uuid */
            endpoint_id?: string;
            /** Format: uuid */
            event_id: string;
            event_type: components["schemas"]["WebhookEventType"];
            /** Format: uuid */
            intent_id: string;
            status: components["schemas"]["WebhookDeliveryStatus"];
            attempts: number;
            /** Format: date-time */
            next_attempt_at?: string | null;
            last_status_code?: number | null;
            last_error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at?: string | null;
        };
        MonitorIntent: {
            /** Format: uuid */
            intent_id: string;
            status: components["schemas"]["IntentStatus"];
            /** @description Recipient with middle digits hidden, for example +9665•••••001. */
            to_masked: string;
            agent_id: string | null;
            /** Format: uuid */
            department_id?: string | null;
            purpose_code: string | null;
            masked_reference?: string | null;
            priority: components["schemas"]["Priority"];
            verification_level: components["schemas"]["VerificationLevel"];
            channel_used?: components["schemas"]["Channel"] | null;
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_until: string;
            scheduled_slot?: components["schemas"]["Slot"] | null;
            decline_reason?: string | null;
            outcome_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MonitorIntentDetail: components["schemas"]["MonitorIntent"] & {
            proposed_slots?: components["schemas"]["Slot"][];
            events: components["schemas"]["IntentEvent"][];
            delivery_attempts: {
                channel: string;
                outcome: string;
                reason?: string | null;
                /** Format: date-time */
                at: string;
            }[];
            webhooks: components["schemas"]["WebhookDelivery"][];
        };
        MonitorSummary: {
            /** Format: date-time */
            since: string;
            total: number;
            by_status: {
                [key: string]: number;
            };
            by_channel: {
                [key: string]: number;
            };
        };
        AuditEvent: {
            /** Format: uuid */
            event_id: string;
            /** Format: date-time */
            at: string;
            actor: string;
            action: string;
            object_type: string;
            object_id: string;
            reason?: string | null;
            hash: string;
            prev_hash: string;
        };
        ReviewQueue: {
            verifications: {
                /** Format: uuid */
                request_id: string;
                /** Format: uuid */
                tenant_id: string;
                legal_name: components["schemas"]["LocalisedText"];
                sector: components["schemas"]["Sector"];
                /** Format: date-time */
                submitted_at: string;
            }[];
            purpose_codes: (components["schemas"]["AdminPurposeCode"] & {
                /** Format: uuid */
                tenant_id: string;
                tenant_name: components["schemas"]["LocalisedText"];
            })[];
            calling_numbers: (components["schemas"]["CallingNumber"] & {
                /** Format: uuid */
                tenant_id: string;
                tenant_name: components["schemas"]["LocalisedText"];
                /** @description Full business number, shown to reviewers only, to check operator registration. */
                phone: string;
            })[];
        };
        LocalisedText: {
            en: string;
            ar: string;
        };
        /** @description RFC 9457 problem details. */
        Problem: {
            /**
             * Format: uri
             * @example https://errors.ringsays.app/invalid-transition
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Stable machine readable error code. */
            code?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        /** @example +966500000000 */
        E164: string;
        /** @enum {string} */
        Priority: "LOW" | "NORMAL" | "IMPORTANT" | "URGENT";
        /** @enum {string} */
        Channel: "VOIP" | "SDK" | "PRECALL_PUSH" | "PSTN" | "PLATFORM_CALLER_ID";
        PurposeCodeFields: {
            code: string;
            display_text: components["schemas"]["LocalisedText"];
            max_priority: components["schemas"]["Priority"];
            max_duration_min: number;
            allowed_channels: components["schemas"]["Channel"][];
        };
        PurposeCode: components["schemas"]["PurposeCodeFields"] & {
            /** @enum {string} */
            status: "PENDING_REVIEW" | "APPROVED" | "REJECTED" | "RETIRED";
            version: number;
        };
        PurposeCodeCreate: components["schemas"]["PurposeCodeFields"];
        /** @enum {string} */
        IntentStatus: "DRAFT" | "REQUESTED" | "DELIVERED" | "ACCEPTED" | "RESCHEDULED" | "DECLINED" | "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "FOLLOW_UP_REQUIRED" | "CANCELLED" | "EXPIRED";
        /**
         * @description Computed by RingSays, never supplied by caller.
         * @enum {string}
         */
        VerificationLevel: "NONE" | "PHONE" | "ORG" | "ORG_AGENT_NUMBER";
        Slot: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        IntentEvent: {
            /** Format: date-time */
            at: string;
            from_status: components["schemas"]["IntentStatus"];
            to_status: components["schemas"]["IntentStatus"];
            /** @enum {string} */
            actor: "CALLER" | "RECEIVER" | "SYSTEM";
        };
    };
    responses: {
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Credentials valid but not allowed for this resource or tenant. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource does not exist or is not visible to caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request conflicts with current state, for example an invalid status transition. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request is well formed but violates a business rule, for example priority above purpose code cap. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TenantId: string;
        NumberId: string;
        DocumentId: string;
        EndpointId: string;
        Code: string;
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Department"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                department_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAgents: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Agent"][];
                        next_cursor: string | null;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listCallingNumbers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calling numbers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CallingNumber"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    addCallingNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallingNumberInput"];
            };
        };
        responses: {
            /** @description Added, status PENDING_VERIFICATION. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallingNumber"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    revokeCallingNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                number_id: components["parameters"]["NumberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallingNumber"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verification"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    uploadVerificationDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    kind: components["schemas"]["DocumentKind"];
                    reference?: string;
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationDocument"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteVerificationDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    submitVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationRequest"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listPortalUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PortalUser"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    invitePortalUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalUserInvite"];
            };
        };
        responses: {
            /** @description Invited. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    updatePortalUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalUserUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalUser"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listTenantPurposeCodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purpose codes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminPurposeCode"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    proposeTenantPurposeCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurposeCodeCreate"];
            };
        };
        responses: {
            /** @description Proposed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPurposeCode"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    retirePurposeCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                code: components["parameters"]["Code"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Retired. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPurposeCode"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listApiClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ApiClient"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createApiClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    label: string;
                    scopes: components["schemas"]["Scope"][];
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiClient"] & {
                        client_secret: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeApiClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiClient"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["WebhookEndpoint"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    events: components["schemas"]["WebhookEventType"][];
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"] & {
                        secret: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    disableWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                endpoint_id: components["parameters"]["EndpointId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Disabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                status?: components["schemas"]["WebhookDeliveryStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                endpoint_id: components["parameters"]["EndpointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deliveries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["WebhookDelivery"][];
                        next_cursor: string | null;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replayWebhookDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                delivery_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDelivery"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    monitorIntents: {
        parameters: {
            query?: {
                status?: components["schemas"]["IntentStatus"][];
                purpose_code?: string;
                agent_id?: string;
                /** @description Exact recipient number; matched by keyed hash, never stored in logs. */
                phone?: components["schemas"]["E164"];
                created_from?: string;
                created_to?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MonitorIntent"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    monitorSummary: {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSummary"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    monitorIntentDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intent detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorIntentDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                action?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEvent"][];
                        next_cursor: string | null;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        intact: boolean;
                        events_checked: number;
                        head: string | null;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    exportAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    backofficeListTenants: {
        parameters: {
            query?: {
                status?: components["schemas"]["TenantStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tenant"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    backofficeCreateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Created with status PENDING. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    backofficeSuspendTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Suspended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    backofficeReinstateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Reinstated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reviewQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueue"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reviewGetVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationReview"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reviewDecideVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Decision recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationRequest"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reviewDownloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reviewPurposeCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantId"];
                code: components["parameters"]["Code"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Decision recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPurposeCode"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reviewCallingNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number_id: components["parameters"]["NumberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Decision recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallingNumber"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
