import type { components } from "./schema";

type S = components["schemas"];
export type Me = S["Me"];
export type Membership = S["Me"]["memberships"][number];
export type Permission = S["Permission"];
export type TenantRole = S["TenantRole"];
export type StaffRole = S["StaffRole"];
export type Tenant = S["Tenant"];
export type Sector = S["Sector"];
export type Department = S["Department"];
export type Agent = S["Agent"];
export type CallingNumber = S["CallingNumber"];
export type DocumentKind = S["DocumentKind"];
export type VerificationDocument = S["VerificationDocument"];
export type VerificationRequest = S["VerificationRequest"];
export type Verification = S["Verification"];
export type PortalUser = S["PortalUser"];
export type AdminPurposeCode = S["AdminPurposeCode"];
export type ApiClient = S["ApiClient"];
export type Scope = S["Scope"];
export type WebhookEndpoint = S["WebhookEndpoint"];
export type WebhookEventType = S["WebhookEventType"];
export type WebhookDelivery = S["WebhookDelivery"];
export type WebhookDeliveryStatus = S["WebhookDeliveryStatus"];
export type MonitorIntent = S["MonitorIntent"];
export type MonitorIntentDetail = S["MonitorIntentDetail"];
export type MonitorSummary = S["MonitorSummary"];
export type AuditEvent = S["AuditEvent"];
export type ReviewQueue = S["ReviewQueue"];
export type VerificationReview = S["VerificationReview"];
export type LocalisedText = { en: string; ar: string };
export type Problem = {
  type?: string;
  title?: string;
  status: number;
  code?: string;
  detail?: string;
  errors?: { field: string; message: string }[];
};
