/** Built in Arabic and English texts. Organisations can override any key through `strings`. */
export const strings = {
  en: {
    verified: "Verified by RingSays",
    verifiedNumber: "Organisation and number verified by RingSays",
    unverified: "Not verified",
    urgent: "Urgent",
    important: "Important",
    from: "From {name}",
    duration: "About {minutes} min",
    endsIn: "Ends in {minutes} min",
    ended: "This request has ended",
    reference: "Reference ending {ref}",
    talkNow: "Talk now",
    later: "Later",
    laterIn: "In {minutes} min",
    propose: "Suggest times",
    send: "Send",
    schedule: "Pick a time",
    message: "Message me instead",
    decline: "Decline",
    declined: "Declined",
    answered: "Answer sent",
    accepted: "You accepted. Expect the call shortly.",
    rescheduled: "You asked for another time.",
    scheduled: "Call scheduled.",
    cancel: "Cancel",
    error: "Something went wrong. Please try again.",
    network: "No connection. Please try again.",
    notForThisDevice: "This request is shown on another device.",
    loading: "Loading…",
  },
  ar: {
    verified: "موثّق من رينغ سيز",
    verifiedNumber: "المنشأة والرقم موثّقان من رينغ سيز",
    unverified: "غير موثّق",
    urgent: "عاجل",
    important: "مهم",
    from: "من {name}",
    duration: "حوالي {minutes} دقيقة",
    endsIn: "ينتهي بعد {minutes} دقيقة",
    ended: "انتهى هذا الطلب",
    reference: "المرجع ينتهي بـ {ref}",
    talkNow: "تحدّث الآن",
    later: "لاحقًا",
    laterIn: "بعد {minutes} دقيقة",
    propose: "اقترح أوقاتًا",
    send: "إرسال",
    schedule: "اختر وقتًا",
    message: "راسلني بدلًا من الاتصال",
    decline: "رفض",
    declined: "مرفوض",
    answered: "تم إرسال ردك",
    accepted: "قبلت. توقّع الاتصال قريبًا.",
    rescheduled: "طلبت وقتًا آخر.",
    scheduled: "تمت جدولة المكالمة.",
    cancel: "إلغاء",
    error: "حدث خطأ. حاول مرة أخرى.",
    network: "لا يوجد اتصال. حاول مرة أخرى.",
    notForThisDevice: "هذا الطلب معروض على جهاز آخر.",
    loading: "جارٍ التحميل…",
  },
} as const;

export type StringKey = keyof (typeof strings)["en"];
export type Strings = Record<StringKey, string>;

export function format(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ""));
}
