/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send one time code to phone */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify code and register device */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update push tokens for a device */
        put: operations["updatePushTokens"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incoming and outgoing intents, cursor synced */
        get: operations["getInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/intents/{intent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One intent addressed to signed in user */
        get: operations["getMyIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Context Token to display payload (enterprise SDK)
         * @description Used by the enterprise SDK inside the tenant's own app; no RingSays account needed.
         *     First resolve binds the token to `RingSays-Device-Id` (SDK install id); other devices are refused.
         *     Refused after intent completion or expiry. Before the intent window opens, the resolve binds the
         *     device and returns status REQUESTED; delivery happens when the window opens.
         *
         */
        get: operations["resolveContextToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{token}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond to an intent from the enterprise SDK */
        post: operations["respondViaContextToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intents/{intent_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receiver response to an intent */
        post: operations["respondToIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get communication rules */
        get: operations["getPreferences"];
        /** Replace communication rules */
        put: operations["putPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List consents granted by user */
        get: operations["listConsents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consents/{consent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraw a consent */
        delete: operations["withdrawConsent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download all personal data RingSays holds for this user */
        post: operations["requestExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Erase account and all personal data */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeviceRegistration: {
            /** @enum {string} */
            platform: "IOS" | "ANDROID";
            /** @description Base64 encoded P-256 public key generated in secure enclave or keystore. */
            public_key: string;
            app_version: string;
            push?: components["schemas"]["PushTokens"];
        };
        PushTokens: {
            apns?: string;
            pushkit?: string;
            fcm?: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            expires_in: number;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            device_id: string;
        };
        IntentDisplay: {
            intent_id: components["schemas"]["IntentId"];
            status: components["schemas"]["IntentStatus"];
            /** Format: date-time */
            created_at?: string;
            scheduled_slot?: components["schemas"]["Slot"] | null;
            proposed_slots?: components["schemas"]["Slot"][];
            organisation_name?: string | null;
            department_name?: string | null;
            agent_display_name?: string | null;
            verification_level: components["schemas"]["VerificationLevel"];
            intent_source: components["schemas"]["IntentSource"];
            /** @description Rendered from approved template in requested language. */
            why?: string | null;
            /** @description Consumer free text. Clients must render in unverified style. */
            unverified_subject?: string | null;
            masked_reference?: string | null;
            priority: components["schemas"]["Priority"];
            expected_duration_min: number;
            /** Format: date-time */
            valid_until: string;
            /** Format: uri */
            deep_link?: string | null;
            actions: ("TALK_NOW" | "LATER" | "PROPOSE" | "SCHEDULE" | "MESSAGE" | "DECLINE")[];
        };
        IntentResponse: {
            /** @enum {string} */
            action: "ACCEPT" | "LATER" | "PROPOSE" | "SCHEDULE" | "MESSAGE" | "DECLINE";
            /** @enum {integer} */
            later_minutes?: 15 | 30 | 60 | 120;
            proposed_slots?: components["schemas"]["Slot"][];
            /** @description For SCHEDULE, one of the slots offered by caller. */
            slot?: components["schemas"]["Slot"];
            decline_reason?: components["schemas"]["DeclineReason"];
        };
        TimeWindow: {
            days: ("MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN")[];
            start: string;
            end: string;
        };
        Preferences: {
            /** @example Asia/Riyadh */
            timezone: string;
            /** @default false */
            verified_businesses_only: boolean;
            night_mode?: components["schemas"]["TimeWindow"] | null;
            rules: {
                match: {
                    /** @enum {string} */
                    category?: "WORK" | "FAMILY" | "UNKNOWN" | "SALES" | "DELIVERY" | "BANK" | "GOVERNMENT";
                    min_verification?: components["schemas"]["VerificationLevel"];
                    min_priority?: components["schemas"]["Priority"];
                    max_duration_min?: number;
                };
                window?: components["schemas"]["TimeWindow"] | null;
                /** @enum {string} */
                action: "ALLOW" | "HOLD_UNTIL_WINDOW" | "REQUEST_FIRST" | "MESSAGE_ONLY" | "BLOCK";
            }[];
        };
        Consent: {
            /** Format: uuid */
            consent_id: string;
            /** @description Organisation display name */
            grantee: string;
            purpose: string;
            scope?: string;
            /** Format: date-time */
            granted_at: string;
            /** Format: date-time */
            withdrawn_at?: string | null;
        };
        /** @example +966500000000 */
        E164: string;
        /** @description RFC 9457 problem details. */
        Problem: {
            /**
             * Format: uri
             * @example https://errors.ringsays.app/invalid-transition
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Stable machine readable error code. */
            code?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        /**
         * Format: uuid
         * @description UUIDv7, time ordered.
         */
        IntentId: string;
        /** @enum {string} */
        IntentStatus: "DRAFT" | "REQUESTED" | "DELIVERED" | "ACCEPTED" | "RESCHEDULED" | "DECLINED" | "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "FOLLOW_UP_REQUIRED" | "CANCELLED" | "EXPIRED";
        Slot: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        /**
         * @description Computed by RingSays, never supplied by caller.
         * @enum {string}
         */
        VerificationLevel: "NONE" | "PHONE" | "ORG" | "ORG_AGENT_NUMBER";
        /**
         * @description Whether reason was declared by caller, predicted by RingSays, or unknown. Predicted reasons are never shown as declared.
         * @enum {string}
         */
        IntentSource: "DECLARED" | "PREDICTED" | "UNKNOWN";
        /** @enum {string} */
        Priority: "LOW" | "NORMAL" | "IMPORTANT" | "URGENT";
        /** @enum {string} */
        DeclineReason: "NOT_INTERESTED" | "WRONG_PERSON" | "ALREADY_RESOLVED" | "NOT_NOW" | "MESSAGE_INSTEAD" | "OTHER";
    };
    responses: {
        /** @description Rate limit or quota exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource does not exist or is not visible to caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Credentials valid but not allowed for this resource or tenant. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource has expired. */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request conflicts with current state, for example an invalid status transition. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request is well formed but violates a business rule, for example priority above purpose code cap. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description SDK installation id (UUID), generated once per app install. */
        DeviceId: string;
        Cursor: string;
        Limit: number;
        /** @description Standard Accept-Language header (for example `ar-SA`, `en-US,en;q=0.9`). Text is rendered in the
         *     first listed language whose primary subtag is ar or en; otherwise Arabic.
         *      */
        AcceptLanguage: string;
        IntentId: components["schemas"]["IntentId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: components["schemas"]["E164"];
                    /** @enum {string} */
                    locale?: "en" | "ar";
                };
            };
        };
        responses: {
            /** @description Code sent if number is valid. Response identical either way to prevent enumeration. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        challenge_id: string;
                        expires_in: number;
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    challenge_id: string;
                    code: string;
                    device: components["schemas"]["DeviceRegistration"];
                };
            };
        };
        responses: {
            /** @description Verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                    /** @description Signature over refresh token with device private key. */
                    device_signature: string;
                };
            };
        };
        responses: {
            /** @description New token pair; old refresh token revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePushTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokens"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getInbox: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                folder?: "REQUESTS" | "SCHEDULED" | "HISTORY";
            };
            header?: {
                /** @description Standard Accept-Language header (for example `ar-SA`, `en-US,en;q=0.9`). Text is rendered in the
                 *     first listed language whose primary subtag is ar or en; otherwise Arabic.
                 *      */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inbox page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["IntentDisplay"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    getMyIntent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Standard Accept-Language header (for example `ar-SA`, `en-US,en;q=0.9`). Text is rendered in the
                 *     first listed language whose primary subtag is ar or en; otherwise Arabic.
                 *      */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                intent_id: components["parameters"]["IntentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intent display. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDisplay"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resolveContextToken: {
        parameters: {
            query?: never;
            header: {
                /** @description SDK installation id (UUID), generated once per app install. */
                "RingSays-Device-Id": components["parameters"]["DeviceId"];
                /** @description Standard Accept-Language header (for example `ar-SA`, `en-US,en;q=0.9`). Text is rendered in the
                 *     first listed language whose primary subtag is ar or en; otherwise Arabic.
                 *      */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Display payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDisplay"];
                };
            };
            403: components["responses"]["Forbidden"];
            410: components["responses"]["Gone"];
        };
    };
    respondViaContextToken: {
        parameters: {
            query?: never;
            header: {
                /** @description SDK installation id (UUID), generated once per app install. */
                "RingSays-Device-Id": components["parameters"]["DeviceId"];
                /** @description Standard Accept-Language header (for example `ar-SA`, `en-US,en;q=0.9`). Text is rendered in the
                 *     first listed language whose primary subtag is ar or en; otherwise Arabic.
                 *      */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentResponse"];
            };
        };
        responses: {
            /** @description Response applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDisplay"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["Gone"];
        };
    };
    respondToIntent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Standard Accept-Language header (for example `ar-SA`, `en-US,en;q=0.9`). Text is rendered in the
                 *     first listed language whose primary subtag is ar or en; otherwise Arabic.
                 *      */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                intent_id: components["parameters"]["IntentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentResponse"];
            };
        };
        responses: {
            /** @description Response applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDisplay"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["Gone"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules. ETag header carries version for If-Match. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
        };
    };
    putPreferences: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description ETag mismatch. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consents granted by user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Consent"][];
                    };
                };
            };
        };
    };
    withdrawConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    requestExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        generated_at: string;
                        profile: Record<string, never>;
                        devices: Record<string, never>[];
                        preferences: components["schemas"]["Preferences"];
                        consents: components["schemas"]["Consent"][];
                        communications_received: Record<string, never>[];
                        /** @constant */
                        address_book?: "never collected";
                    };
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Erasure scheduled; completes within retention SLA. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
